[tool.pytest.ini_options]
addopts = "--tb native -v -r fxX --maxfail=100 -p no:warnings --log-info=sqlalchemy.engine "

markers = [
    "backend: mark test as for the backend",
]

python_files = "test/*test_*.py"

[build-system]
requires = ["setuptools>=61.0", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "sqlalchemy-firebird"
description = "Firebird for SQLAlchemy"
requires-python = ">=3.11"
keywords = ["SQLAlchemy", "Firebird", "firebird-driver"]
license = {file = "LICENSE"}
authors = [
    {name = "F.D.Castel", email = "fdcastel@gmail.com"},
]
maintainers = [
    {name = "F.D.Castel", email = "fdcastel@gmail.com"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Database :: Front-Ends",
    "Operating System :: OS Independent",
]
dependencies = [
    "SQLAlchemy >= 2.0",
    "firebird-driver",
    "packaging",
]
dynamic = ["readme", "version"]

[dependency-groups]
dev = ["pytest", "ruff"]

[project.urls]
Documentation = "https://github.com/fdcastel/sqlalchemy-firebird/wiki"
Source = "https://github.com/fdcastel/sqlalchemy-firebird"
Tracker = "https://github.com/fdcastel/sqlalchemy-firebird/issues"

[project.entry-points."sqlalchemy.dialects"]
"firebird" = "sqlalchemy_firebird.firebird:FBDialect_firebird"
"firebird.firebird" = "sqlalchemy_firebird.firebird:FBDialect_firebird"

[tool.setuptools.dynamic]
readme = {file = ["README.md"], content-type = "text/markdown"}

[tool.setuptools.packages.find]
include = ["sqlalchemy_firebird*"]

[tool.setuptools_scm]
version_file = "sqlalchemy_firebird/_version.py"

[tool.ruff]
target-version = "py311"
line-length = 79

[tool.ruff.lint]
ignore = ["E203", "E266", "E501", "E722", "F401", "F403", "F405", "F811", "F841"]

[tool.ruff.format]
