"""
.. dialect:: firebird+firebird
    :name: firebird
    :dbapi: firebird-driver
    :connectstring: firebird+firebird://user:password@host:port/path/to/db[?key=value&key=value...]
    :url: https://pypi.org/project/firebird-driver/
    :documentation: https://firebird-driver.readthedocs.io/en/latest/

    This dialect targets Firebird 3.0 and newer through the ``firebird-driver``
    package (Python 3.11+), which uses the modern Firebird OO API exposed by the
    ``fbclient`` library.

Connection strings
------------------

A SQLAlchemy URL has the shape
``firebird+firebird://username:password@host:port/database``::

    # Remote server (default port 3050)
    firebird+firebird://sysdba:masterkey@dbhost/path/to/project.fdb

    # Embedded server -- omit host/port and point fb_client_library at fbclient
    firebird+firebird://sysdba@/path/to/project.fdb?fb_client_library=/opt/firebird/lib/libfbclient.so

Useful query parameters:

* ``charset`` -- character set of the database (Firebird default ``UTF8``).
* ``fb_client_library`` -- full path to the client library
  (``libfbclient.so`` / ``fbclient.dll``). Required for embedded servers or a
  non-default client install. This is necessarily process-global: only one
  native ``fbclient`` can be loaded per process.

Supported versions and version-gated features
---------------------------------------------

The dialect adapts its SQL to ``server_version_info``:

* **Identity columns** -- Firebird 3.0 only supports ``GENERATED BY DEFAULT AS
  IDENTITY`` (no ``ALWAYS``) and ignores ``INCREMENT BY``; ``START WITH`` also
  has different semantics. Firebird 4.0+ supports ``GENERATED ALWAYS`` and
  ``INCREMENT BY``.
* **INT128, DECFLOAT(16|34), TIME / TIMESTAMP WITH TIME ZONE** -- Firebird 4.0+.
* **BINARY / VARBINARY** -- native on Firebird 4.0+; emulated as
  ``CHAR/VARCHAR CHARACTER SET OCTETS`` on Firebird 3.0.
* **UUID** -- stored in its canonical 16-byte form: ``BINARY(16)`` on Firebird
  4.0+, ``CHAR(16) CHARACTER SET OCTETS`` on Firebird 3.0 (see
  :class:`~sqlalchemy_firebird.types.FBUUID`).
* **Partial indexes** (an index ``WHERE`` predicate) -- Firebird 5.0+.
* **Multi-row RETURNING** -- Firebird 5.0+. (Single-row ``RETURNING`` on
  ``INSERT``/``UPDATE``/``DELETE`` works on all supported versions.)

Dialect-specific construct arguments
------------------------------------

* :class:`~sqlalchemy.schema.Index` accepts ``firebird_descending=True``
  (emits ``CREATE DESCENDING INDEX``) and ``firebird_where=<expr>`` (a partial
  index predicate, Firebird 5.0+).
* :class:`~sqlalchemy.schema.Table` accepts
  ``firebird_on_commit="PRESERVE ROWS"`` / ``"DELETE ROWS"`` for global
  temporary tables (combined with ``prefixes=["GLOBAL TEMPORARY"]``).

Isolation levels and read-only transactions
--------------------------------------------

Set the isolation level on the engine or per-connection::

    engine = create_engine(url, isolation_level="REPEATABLE READ")
    conn = engine.connect().execution_options(isolation_level="SERIALIZABLE")

Firebird applies isolation, read-only access and auto-commit per transaction
through the Transaction Parameter Buffer (TPB); there is no per-connection
``SET TRANSACTION ISOLATION``. Supported levels: ``READ COMMITTED`` (the
default, mapped to ``READ COMMITTED RECORD VERSION``), ``REPEATABLE READ``
(Firebird ``SNAPSHOT``), ``SERIALIZABLE`` (snapshot table stability) and
``AUTOCOMMIT``.

Read-only transactions are exposed through the ``firebird_readonly`` execution
option::

    ro = conn.execution_options(firebird_readonly=True)

Reflection extras
-----------------

Beyond the standard inspector methods, :class:`.FBInspector` adds Firebird
specific reflection reachable via ``inspect(engine)``:

* ``get_domains()`` -- the database's domains
  (:class:`~sqlalchemy_firebird.base.ReflectedDomain`).
* ``get_sequences()`` -- sequences with their start value and increment
  (:class:`~sqlalchemy_firebird.base.ReflectedSequence`).
"""  # noqa

import sys

from datetime import datetime
from datetime import time
from math import modf
from sqlalchemy.engine import characteristics
from .base import FBDialect

import firebird.driver
from firebird.driver import driver_config
from firebird.driver import get_timezone
from firebird.driver import Isolation
from firebird.driver import TPB
from firebird.driver import TraAccessMode


# Firebird applies isolation, read-only access and (FB) auto-commit per
# transaction via the Transaction Parameter Buffer (TPB); there is no
# per-connection "SET TRANSACTION ISOLATION". Map SQLAlchemy's isolation
# level names to the firebird-driver Isolation members.
FB_ISOLATION_LEVEL = {
    "READ COMMITTED": Isolation.READ_COMMITTED_RECORD_VERSION,
    "REPEATABLE READ": Isolation.SNAPSHOT,
    "SERIALIZABLE": Isolation.SERIALIZABLE,
}

# Firebird's practical default for an ORM workload (also SQLAlchemy's
# conventional default across backends).
FB_DEFAULT_ISOLATION_LEVEL = "READ COMMITTED"


class FBReadOnlyConnectionCharacteristic(
    characteristics.ConnectionCharacteristic
):
    """Expose Firebird read-only transactions via the ``firebird_readonly``
    execution option, mirroring PostgreSQL's ``postgresql_readonly``."""

    transactional = True

    def reset_characteristic(self, dialect, dbapi_conn):
        dialect.set_readonly(dbapi_conn, False)

    def set_characteristic(self, dialect, dbapi_conn, value):
        dialect.set_readonly(dbapi_conn, value)

    def get_characteristic(self, dialect, dbapi_conn):
        return dialect.get_readonly(dbapi_conn)


class FBDialect_firebird(FBDialect):
    driver = "firebird"
    supports_statement_cache = True

    connection_characteristics = FBDialect.connection_characteristics.union(
        {"firebird_readonly": FBReadOnlyConnectionCharacteristic()}
    )

    @classmethod
    def import_dbapi(cls):
        return firebird.driver

    # -- Transaction options: isolation level, AUTOCOMMIT and read-only ----
    #
    # Firebird has no per-connection isolation switch: isolation, read-only
    # access and (FB) auto-commit are all properties of the TPB used to start
    # a transaction. We track the requested options on the DBAPI connection
    # and keep its main transaction's ``default_tpb`` in sync, so the next
    # transaction the driver starts uses them. The requested options are also
    # stored on the connection so ``get_isolation_level`` / ``get_readonly``
    # can report them back.

    def on_connect(self):
        def connect(dbapi_connection):
            dbapi_connection._sa_isolation_level = FB_DEFAULT_ISOLATION_LEVEL
            dbapi_connection._sa_readonly = False
            self._apply_transaction_options(dbapi_connection)

        return connect

    def _apply_transaction_options(self, dbapi_connection):
        level = getattr(
            dbapi_connection,
            "_sa_isolation_level",
            FB_DEFAULT_ISOLATION_LEVEL,
        )
        readonly = getattr(dbapi_connection, "_sa_readonly", False)

        # AUTOCOMMIT is the TPB auto-commit flag layered on a base isolation;
        # the server commits the work of each statement automatically.
        auto_commit = level == "AUTOCOMMIT"
        isolation = FB_ISOLATION_LEVEL[
            FB_DEFAULT_ISOLATION_LEVEL if auto_commit else level
        ]
        access_mode = TraAccessMode.READ if readonly else TraAccessMode.WRITE

        default_tpb = TPB(
            isolation=isolation,
            access_mode=access_mode,
            auto_commit=auto_commit,
        ).get_buffer()

        # ``default_tpb`` governs the next transaction the driver starts.
        # SQLAlchemy applies these options before any transaction begins (on
        # connect, and while resetting/changing execution options), so the new
        # options take effect from the next statement onward.
        dbapi_connection.main_transaction.default_tpb = default_tpb

    def get_isolation_level_values(self, dbapi_connection):
        return list(FB_ISOLATION_LEVEL) + ["AUTOCOMMIT"]

    def get_default_isolation_level(self, dbapi_connection):
        return FB_DEFAULT_ISOLATION_LEVEL

    def get_isolation_level(self, dbapi_connection):
        return getattr(
            dbapi_connection,
            "_sa_isolation_level",
            FB_DEFAULT_ISOLATION_LEVEL,
        )

    def set_isolation_level(self, dbapi_connection, level):
        dbapi_connection._sa_isolation_level = level
        self._apply_transaction_options(dbapi_connection)

    def reset_isolation_level(self, dbapi_connection):
        # Restore the engine-level isolation_level if one was configured,
        # else the dialect default. The base implementation asserts that any
        # engine-level value is the default or AUTOCOMMIT; Firebird supports
        # restoring an arbitrary configured level across pooled connections
        # (independent_readonly_connections), so we relax that assertion.
        level = (
            self._on_connect_isolation_level
            if self._on_connect_isolation_level is not None
            else self.default_isolation_level
        )
        self._assert_and_set_isolation_level(dbapi_connection, level)

    def get_readonly(self, dbapi_connection):
        return getattr(dbapi_connection, "_sa_readonly", False)

    def set_readonly(self, dbapi_connection, value):
        dbapi_connection._sa_readonly = value
        self._apply_transaction_options(dbapi_connection)

    def create_connect_args(self, url):
        opts = url.translate_connect_args(username="user")

        qry = url.query
        if qry.get("fb_client_library"):
            # firebird-driver loads a single native fbclient per process, so
            # fb_client_library is inherently process-global: all engines in a
            # process must agree on it. Set it and remove it from the keys
            # passed to .connect().
            driver_config.fb_client_library.value = qry["fb_client_library"]
            qry = remove_keys(qry, {"fb_client_library"})

        if opts.get("host"):
            host_name = opts["host"]
            database_name = opts["database"]

            port_number = "3050"
            if opts.get("port") is not None:
                port_number = str(opts["port"])
                del opts["port"]

            # Key the driver_config server registration by "host/port" so
            # multiple Firebird servers on the same host (different ports)
            # get distinct entries (issue #69). The "/" separator matches
            # Firebird's host/port syntax and never collides with the colons
            # in IPv6 literals, so no special-casing is required.
            server_name = f"{host_name}/{port_number}"

            cfg_driver_server = driver_config.get_server(server_name)
            if cfg_driver_server is None:
                cfg_driver_server = driver_config.register_server(server_name)
            cfg_driver_server.host.value = host_name
            cfg_driver_server.port.value = port_number

            # driver_config is process-global. Key the database registration
            # by "server/database" rather than the database path alone, so two
            # engines pointing at the same database path on different servers
            # don't clobber each other's server mapping (A7). The config name
            # is just an internal key; the real path lives in database.value.
            database_key = f"{server_name}/{database_name}"

            cfg_driver_database = driver_config.get_database(database_key)
            if cfg_driver_database is None:
                cfg_driver_database = driver_config.register_database(
                    database_key
                )
            cfg_driver_database.server.value = server_name
            cfg_driver_database.database.value = database_name

            # Connect via the registered config name.
            opts["database"] = database_key
            del opts["host"]

        opts.update(qry)
        return ([], opts)

    def do_rollback(self, dbapi_connection):
        if dbapi_connection.is_active():
            dbapi_connection.rollback()

    def do_commit(self, dbapi_connection):
        if dbapi_connection.is_active():
            dbapi_connection.commit()

    def _get_server_version_info(self, connection):
        dbapi_connection = connection.connection.dbapi_connection
        minor, major = modf(dbapi_connection.info.engine_version)
        return (int(major), int(minor * 10))

    def adapt_timezone(self, param):
        # Convert tzinfo for firebird-driver. Requires tzinfo.tzname() method implemented.
        if isinstance(param, datetime) and param.tzinfo:
            return param.replace(tzinfo=get_timezone(param.tzname()))
        elif isinstance(param, time) and param.tzinfo:
            return param.replace(tzinfo=get_timezone(param.tzname()))
        return param

    def do_execute(self, cursor, statement, parameters, context=None):
        # Firebird-driver needs special time zone handling.
        #   https://github.com/FirebirdSQL/python3-driver/issues/19#issuecomment-1523045743
        adapted_parameters = [self.adapt_timezone(p) for p in parameters]
        self._disable_blob_streaming(cursor)
        super().do_execute(cursor, statement, adapted_parameters, context)

    def do_executemany(self, cursor, statement, parameters, context=None):
        self._disable_blob_streaming(cursor)
        super().do_executemany(cursor, statement, parameters, context)

    def do_execute_no_params(self, cursor, statement, context=None):
        self._disable_blob_streaming(cursor)
        super().do_execute_no_params(cursor, statement, context)

    @staticmethod
    def _disable_blob_streaming(cursor):
        # SQLAlchemy fully consumes a cursor and then closes it before its
        # result processors run. firebird-driver closes any BlobReader
        # objects together with the cursor, which would make BLOB columns
        # unreadable from within SQLAlchemy result rows (issue #58). Force
        # all BLOBs to be returned as fully materialized bytes/str by
        # raising the per-cursor streaming threshold past any practical
        # size; this leaves driver_config.stream_blob_threshold untouched.
        if hasattr(cursor, "stream_blob_threshold"):
            cursor.stream_blob_threshold = sys.maxsize


def remove_keys(d, keys):
    return {x: d[x] for x in d if x not in keys}


dialect = FBDialect_firebird
